import { Lead, Task, Contract, CustomField, LeadScoreTrigger, Squad, LeadActivity, FinanceEntry, GlobalWebhook, Notification, Appointment } from '../types';

export const defaultCustomLeadFields: CustomField[] = [];
export const defaultLeadScoreTriggers: LeadScoreTrigger[] = [];
export const defaultFinanceEntries: FinanceEntry[] = [];
export const defaultGlobalWebhooks: GlobalWebhook[] = [];

export const defaultLeads: Lead[] = [
  {
    id: "lead-1",
    name: "Ana Carolina Ferraz",
    company: "Nexus Automação Industrial",
    email: "ana.ferraz@nexusauto.com.br",
    phone: "(11) 98765-4321",
    status: "Em Aberto",
    value: "R$ 48.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Lucas Martins",
    source: "Google Ads",
    title: "Implantação ERP + CRM S.P.Y.",
    priority: "Alta",
    stageId: "1",
    pipelineId: "comercial",
    scoreIA: 94,
    temperature: "quente",
    iaSummary: "Diretoria busca substituir sistema legado por solução integrada S.P.Y.. Orçamento aprovado.",
    timeIdle: 2,
    tags: ["Decisor", "Enterprise", "Prioritário"],
    clientName: "Alpha Tech Soluções",
  },
  {
    id: "lead-2",
    name: "Rodrigo Mendonça",
    company: "Solaris Energia Sustentável",
    email: "rodrigo@solarisenergia.com",
    phone: "(21) 99876-5432",
    status: "Em Aberto",
    value: "R$ 32.500,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Mariana Rios",
    source: "Instagram",
    title: "Gestão de Equipe Externa & Propostas",
    priority: "Média",
    stageId: "2",
    pipelineId: "comercial",
    scoreIA: 82,
    temperature: "quente",
    iaSummary: "Reunião de diagnóstico realizada. Solicitou minuta de contrato com módulos de CRM e Finanças.",
    timeIdle: 5,
    tags: ["Solar", "Mid-Market"],
  },
  {
    id: "lead-3",
    name: "Camila Guimarães",
    company: "Hospitalar Care Diagnósticos",
    email: "camila.g@carehosp.com.br",
    phone: "(31) 97654-3210",
    status: "Em Aberto",
    value: "R$ 64.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Carlos Mendes",
    source: "Indicação",
    title: "Licença S.P.Y. Saúde + Telemedicina",
    priority: "Alta",
    stageId: "3",
    pipelineId: "comercial",
    scoreIA: 88,
    temperature: "quente",
    iaSummary: "Proposta técnica apresentada. Negociando termo de confidencialidade e SLA de atendimento.",
    timeIdle: 1,
    tags: ["Saúde", "Telemedicina", "VIP"],
    clientName: "Gama Saúde Hospitalar",
  },
  {
    id: "lead-4",
    name: "Guilherme Siqueira",
    company: "Vanguard Logística Integrada",
    email: "guilherme@vanguardlog.com",
    phone: "(41) 98877-6655",
    status: "Em Aberto",
    value: "R$ 21.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Fernanda Lima",
    source: "WhatsApp",
    title: "Controle de Frotas & Operações",
    priority: "Baixa",
    stageId: "4",
    pipelineId: "comercial",
    scoreIA: 65,
    temperature: "morno",
    iaSummary: "Em fase de revisão orçamentária para o próximo trimestre.",
    timeIdle: 8,
    tags: ["Logística", "Follow-up"],
  },
  {
    id: "lead-5",
    name: "Juliana Peixoto",
    company: "EducaTech Cursos & Treinamentos",
    email: "juliana@educatech.org.br",
    phone: "(19) 99123-4567",
    status: "Fechado",
    value: "R$ 55.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Lucas Martins",
    source: "Site / Orgânico",
    title: "Portal EAD + Certificação S.P.Y.",
    priority: "Alta",
    stageId: "5",
    pipelineId: "comercial",
    scoreIA: 98,
    temperature: "quente",
    iaSummary: "Contrato assinado! Onboarding agendado para o time acadêmico.",
    timeIdle: 0,
    tags: ["Educação", "Ganhos", "Contrato Fechado"],
  },
  {
    id: "lead-6",
    name: "Eduardo Fontes",
    company: "Prime Imóveis & Incorporações",
    email: "eduardo@primeimoveis.com",
    phone: "(11) 97766-5544",
    status: "Em Aberto",
    value: "R$ 18.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Beatriz Oliveira",
    source: "Instagram",
    title: "Lead Inbound - Triagem Inicial",
    priority: "Alta",
    stageId: "sdr-1",
    pipelineId: "sdr",
    scoreIA: 91,
    temperature: "quente",
    iaSummary: "Lead preencheu formulário buscando automação de corretores e espelho de vendas.",
    timeIdle: 0.5,
    tags: ["Imobiliário", "SDR"],
  },
  {
    id: "lead-7",
    name: "Patrícia Albuquerque",
    company: "Omni Store Cosméticos",
    email: "patricia@omnistore.com.br",
    phone: "(21) 98112-3344",
    status: "Em Aberto",
    value: "R$ 15.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Thiago Rocha",
    source: "WhatsApp",
    title: "Contato Efetuado - Qualificação SDR",
    priority: "Média",
    stageId: "sdr-2",
    pipelineId: "sdr",
    scoreIA: 78,
    temperature: "morno",
    iaSummary: "Primeiro contato telefônico realizado. Validando número de vendedores e demanda de CRM.",
    timeIdle: 3,
    tags: ["Varejo", "SDR"],
  },
  {
    id: "lead-8",
    name: "Marcos Vinicius Tavares",
    company: "AgroForte Insumos Agrícolas",
    email: "marcos@agroforte.com.br",
    phone: "(62) 99334-5566",
    status: "Em Aberto",
    value: "R$ 42.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Juliana Mendes",
    source: "LinkedIn",
    title: "Lead Qualificado SDR ➔ Reunião Marcada",
    priority: "Alta",
    stageId: "sdr-4",
    pipelineId: "sdr",
    scoreIA: 95,
    temperature: "quente",
    iaSummary: "Qualificado pela MIA com 95 pontos. Reunião de demonstração confirmada para amanhã às 15h.",
    timeIdle: 1,
    tags: ["Agronegócio", "Reunião Agendada"],
  },
];

export const defaultTasks: Task[] = [];
export const defaultContracts: Contract[] = [];
export const defaultActivitiesOnLoad: LeadActivity[] = [];
export const getDefaultAppointments = (): Appointment[] => [];
export const defaultSquads: Squad[] = [];
export const defaultNotifications: Notification[] = [];

export const defaultColaboradores: any[] = [];
