import { Lead, Task, Contract, CustomField, LeadScoreTrigger, Squad, LeadActivity, FinanceEntry, GlobalWebhook, Notification, Appointment, Product } from '../types';

export const defaultCustomLeadFields: CustomField[] = [];
export const defaultLeadScoreTriggers: LeadScoreTrigger[] = [];

export const defaultFinanceEntries: FinanceEntry[] = [
  {
    id: "fin-1",
    description: "Mensalidade Enterprise - Nexus Automação",
    value: 4800,
    type: "Receber",
    category: "Receita Recorrente (MRR)",
    date: new Date().toLocaleDateString("pt-BR"),
    status: "Pago",
  },
  {
    id: "fin-2",
    description: "Implantação Módulo Solar - Solaris Energia",
    value: 8500,
    type: "Receber",
    category: "Serviços & Setup",
    date: new Date().toLocaleDateString("pt-BR"),
    status: "Pago",
  },
  {
    id: "fin-3",
    description: "Honorários de Venda Imobiliária - Terraço Jardins",
    value: 55500,
    type: "Receber",
    category: "Comissões Imobiliárias",
    date: "15/09/2026",
    status: "Pendente",
  },
  {
    id: "fin-4",
    description: "Hospedagem em Nuvem & Bancos de Dados AWS",
    value: 2450,
    type: "Pagar",
    category: "Infraestrutura & TI",
    date: "10/09/2026",
    status: "Pendente",
  },
  {
    id: "fin-5",
    description: "Campanhas de Aquisição Google Ads & Meta Ads",
    value: 4200,
    type: "Pagar",
    category: "Marketing & Aquisição",
    date: new Date().toLocaleDateString("pt-BR"),
    status: "Pago",
  },
];

export const defaultGlobalWebhooks: GlobalWebhook[] = [];

export const defaultLeads: Lead[] = [
  {
    id: "lead-1",
    name: "Ana Carolina Ferraz",
    company: "Nexus Automação Industrial",
    email: "ana.ferraz@nexusauto.com.br",
    phone: "(11) 98765-4321",
    status: "Em Aberto",
    value: "R$ 48.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Lucas Martins",
    source: "Google Ads",
    title: "Implantação ERP + CRM S.P.Y.",
    priority: "Alta",
    stageId: "1",
    pipelineId: "comercial",
    scoreIA: 94,
    temperature: "quente",
    iaSummary: "Diretoria busca substituir sistema legado por solução integrada S.P.Y.. Orçamento aprovado.",
    timeIdle: 2,
    tags: ["Decisor", "Enterprise", "Prioritário", "imobiliario"],
    clientName: "Alpha Tech Soluções",
  },
  {
    id: "lead-2",
    name: "Rodrigo Mendonça",
    company: "Solaris Energia Sustentável",
    email: "rodrigo@solarisenergia.com",
    phone: "(21) 99876-5432",
    status: "Em Aberto",
    value: "R$ 32.500,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Mariana Rios",
    source: "Instagram",
    title: "Gestão de Equipe Externa & Propostas",
    priority: "Média",
    stageId: "2",
    pipelineId: "comercial",
    scoreIA: 82,
    temperature: "quente",
    iaSummary: "Reunião de diagnóstico realizada. Solicitou minuta de contrato com módulos de CRM e Finanças.",
    timeIdle: 5,
    tags: ["Solar", "Mid-Market", "solar", "energia-solar"],
  },
  {
    id: "lead-3",
    name: "Camila Guimarães",
    company: "Hospitalar Care Diagnósticos",
    email: "camila.g@carehosp.com.br",
    phone: "(31) 97654-3210",
    status: "Em Aberto",
    value: "R$ 64.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Carlos Mendes",
    source: "Indicação",
    title: "Licença S.P.Y. Saúde + Telemedicina",
    priority: "Alta",
    stageId: "3",
    pipelineId: "comercial",
    scoreIA: 88,
    temperature: "quente",
    iaSummary: "Proposta técnica apresentada. Negociando termo de confidencialidade e SLA de atendimento.",
    timeIdle: 1,
    tags: ["Saúde", "Telemedicina", "VIP", "clinica", "saude"],
    clientName: "Gama Saúde Hospitalar",
  },
  {
    id: "lead-4",
    name: "Guilherme Siqueira",
    company: "Vanguard Veículos & Frotas",
    email: "guilherme@vanguardveiculos.com",
    phone: "(41) 98877-6655",
    status: "Em Aberto",
    value: "R$ 21.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Fernanda Lima",
    source: "WhatsApp",
    title: "Gestão de Concessionária & Pátio",
    priority: "Baixa",
    stageId: "4",
    pipelineId: "comercial",
    scoreIA: 65,
    temperature: "morno",
    iaSummary: "Em fase de revisão orçamentária para o próximo trimestre.",
    timeIdle: 8,
    tags: ["Automotivo", "automotivo", "veiculos", "Follow-up"],
  },
  {
    id: "lead-5",
    name: "Juliana Peixoto",
    company: "EducaTech Cursos & Treinamentos",
    email: "juliana@educatech.org.br",
    phone: "(19) 99123-4567",
    status: "Fechado",
    value: "R$ 55.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Lucas Martins",
    source: "Site / Orgânico",
    title: "Portal EAD + Certificação S.P.Y.",
    priority: "Alta",
    stageId: "5",
    pipelineId: "comercial",
    scoreIA: 98,
    temperature: "quente",
    iaSummary: "Contrato assinado! Onboarding agendado para o time acadêmico.",
    timeIdle: 0,
    tags: ["Educação", "educacao", "Ganhos", "Contrato Fechado"],
  },
  {
    id: "lead-6",
    name: "Eduardo Fontes",
    company: "Prime Imóveis & Incorporações",
    email: "eduardo@primeimoveis.com",
    phone: "(11) 97766-5544",
    status: "Em Aberto",
    value: "R$ 18.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Beatriz Oliveira",
    source: "Instagram",
    title: "Lead Inbound - Triagem Inicial",
    priority: "Alta",
    stageId: "sdr-1",
    pipelineId: "sdr",
    scoreIA: 91,
    temperature: "quente",
    iaSummary: "Lead preencheu formulário buscando automação de corretores e espelho de vendas.",
    timeIdle: 0.5,
    tags: ["Imobiliário", "imobiliario", "SDR"],
  },
  {
    id: "lead-7",
    name: "Patrícia Albuquerque",
    company: "Omni Store Cosméticos & Varejo",
    email: "patricia@omnistore.com.br",
    phone: "(21) 98112-3344",
    status: "Em Aberto",
    value: "R$ 15.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Thiago Rocha",
    source: "WhatsApp",
    title: "Contato Efetuado - Qualificação SDR",
    priority: "Média",
    stageId: "sdr-2",
    pipelineId: "sdr",
    scoreIA: 78,
    temperature: "morno",
    iaSummary: "Primeiro contato telefônico realizado. Validando número de vendedores e demanda de CRM.",
    timeIdle: 3,
    tags: ["Varejo", "varejo", "SDR"],
  },
  {
    id: "lead-8",
    name: "Marcos Vinicius Tavares",
    company: "SolarMax Distribuidora",
    email: "marcos@solarmax.com.br",
    phone: "(62) 99334-5566",
    status: "Em Aberto",
    value: "R$ 42.000,00",
    date: new Date().toLocaleDateString("pt-BR"),
    seller: "Juliana Mendes",
    source: "LinkedIn",
    title: "Lead Qualificado SDR ➔ Reunião Marcada",
    priority: "Alta",
    stageId: "sdr-4",
    pipelineId: "sdr",
    scoreIA: 95,
    temperature: "quente",
    iaSummary: "Qualificado pela Aurora com 95 pontos. Reunião de demonstração confirmada para amanhã às 15h.",
    timeIdle: 1,
    tags: ["Solar", "solar", "energia-solar", "Reunião Agendada"],
  },
];

export const defaultTasks: Task[] = [
  {
    id: "task-1",
    title: "Apresentar Demonstração Comercial S.P.Y.",
    description: "Reunião técnica de diagnóstico e tour guiado pela plataforma.",
    priority: "Alta",
    status: "Pendente",
    dueDate: new Date().toISOString().split("T")[0],
    assignedTo: "Lucas Martins",
  },
  {
    id: "task-2",
    title: "Enviar Minuta de Contrato e Proposta",
    description: "Encaminhar proposta com módulo Financeiro + CRM Integrado.",
    priority: "Média",
    status: "Em Andamento",
    dueDate: new Date().toISOString().split("T")[0],
    assignedTo: "Mariana Rios",
  },
  {
    id: "task-3",
    title: "Configurar Integração de WhatsApp e Webhooks",
    description: "Parametrizar canais oficiais e gatilhos de disparo com o SDR.",
    priority: "Baixa",
    status: "Concluída",
    dueDate: new Date().toISOString().split("T")[0],
    assignedTo: "Carlos Mendes",
  },
];

export const defaultContracts: Contract[] = [
  {
    id: "ct-1",
    client: "Nexus Automação Industrial",
    mrr: 4800,
    status: "Ativo",
    date: "01/08/2026",
    plan: "Plano Enterprise S.P.Y.",
  },
  {
    id: "ct-2",
    client: "Solaris Energia Sustentável",
    mrr: 3500,
    status: "Ativo",
    date: "15/07/2026",
    plan: "Plano Solar Pro",
  },
  {
    id: "ct-3",
    client: "Hospitalar Care Diagnósticos",
    mrr: 7200,
    status: "Ativo",
    date: "20/08/2026",
    plan: "Plano Clínicas & Telemedicina",
  },
  {
    id: "ct-4",
    client: "EducaTech Cursos",
    mrr: 5000,
    status: "Ativo",
    date: "02/09/2026",
    plan: "Plano Acadêmico EAD",
  },
];

export const defaultActivitiesOnLoad: LeadActivity[] = [];

export const getDefaultAppointments = (): Appointment[] => [
  {
    id: "apt-1",
    time: "14:00",
    patient: "Carlos Eduardo Silva",
    patientId: "p-1",
    drId: "dr-1",
    drName: "Dr. Marcelo Fonseca",
    status: "Confirmado",
    type: "Presencial",
    room: "Consultório 102",
    specialty: "Cardiologia",
    phone: "(11) 98765-4321",
    date: new Date().toISOString().split("T")[0],
    notes: "Consulta de rotina com eletrocardiograma.",
  },
  {
    id: "apt-2",
    time: "15:30",
    patient: "Mariana Souza Lima",
    patientId: "p-2",
    drId: "dr-2",
    drName: "Dra. Camila Guimarães",
    status: "Em Atendimento",
    type: "Teleconsulta",
    room: "Sala Virtual A",
    specialty: "Dermatologia",
    phone: "(11) 99876-5432",
    date: new Date().toISOString().split("T")[0],
    notes: "Avaliação de manchas e prescrição de cuidados.",
  },
  {
    id: "apt-3",
    time: "17:00",
    patient: "Fernando Albuquerque",
    patientId: "p-3",
    drId: "dr-3",
    drName: "Dr. Roberto Mendes",
    status: "Finalizado",
    type: "Presencial",
    room: "Consultório 105",
    specialty: "Ortopedia",
    phone: "(11) 97654-3210",
    date: new Date().toISOString().split("T")[0],
    notes: "Retorno pós-exame de ressonância.",
  },
];

export const defaultSquads: Squad[] = [
  {
    id: "sq-1",
    nome: "Squad Vendas Enterprise",
    departamento: "Comercial",
    focoComercial: "Contas Corporativas e Franquias",
    membros: ["Lucas Martins", "Mariana Rios", "Felipe Ramos"],
    leader: "Lucas Martins",
    cor: "#3b82f6",
    faturamentoAlcancado: 142000,
    meta: 150000,
  } as any,
  {
    id: "sq-2",
    nome: "Squad SDR & Inbound Growth",
    departamento: "Pré-Vendas",
    focoComercial: "Qualificação e Agendamentos",
    membros: ["Beatriz Oliveira", "Thiago Rocha"],
    leader: "Beatriz Oliveira",
    cor: "#10b981",
    faturamentoAlcancado: 78000,
    meta: 80000,
  } as any,
];

export const defaultNotifications: Notification[] = [
  {
    id: "notif-1",
    title: "Meta do Mês Próxima!",
    desc: "O Squad Enterprise atingiu 94% da meta mensal.",
    type: "success",
    timestamp: "Há 10 min",
    read: false,
  },
  {
    id: "notif-2",
    title: "Novo Lead Qualificado",
    desc: "Ana Carolina Ferraz foi classificada como Quente pela IA.",
    type: "info",
    timestamp: "Há 25 min",
    read: false,
  },
];

export const defaultColaboradores: any[] = [
  {
    id: "colab-1",
    nome: "Lucas Martins",
    email: "lucas.martins@empresa.com",
    cargo: "Executivo Comercial Senior",
    departamento: "Comercial",
    status: "Ativo",
  },
  {
    id: "colab-2",
    nome: "Mariana Rios",
    email: "mariana.rios@empresa.com",
    cargo: "Closer & Parcerias",
    departamento: "Comercial",
    status: "Ativo",
  },
];

export const defaultProducts: Product[] = [
  {
    id: "prod-1",
    sku: "TECH-SW-01",
    name: "Smartwatch Pro Ultra GPS",
    category: "Eletrônicos",
    type: "Físico",
    price: 389.90,
    cost: 190.00,
    margin: 51.2,
    commission: 5,
    active: true,
    stockMin: 5,
    stockMax: 50,
    currentStock: 24,
    provider: "Global Imports Eletrônicos",
    tags: ["varejo", "mais-vendido", "destaque"],
    typeAttributes: { barcode: "7891234560012", ean: "7891234560012" }
  },
  {
    id: "prod-2",
    sku: "AUD-FONE-02",
    name: "Fone de Ouvido Bluetooth TWS ANC",
    category: "Eletrônicos",
    type: "Físico",
    price: 179.90,
    cost: 75.00,
    margin: 58.3,
    commission: 5,
    active: true,
    stockMin: 10,
    stockMax: 100,
    currentStock: 42,
    provider: "Global Imports Eletrônicos",
    tags: ["varejo", "audio"],
    typeAttributes: { barcode: "7891234560029", ean: "7891234560029" }
  },
  {
    id: "prod-3",
    sku: "ACES-CRG-30",
    name: "Carregador Turbo 30W USB-C PD",
    category: "Acessórios",
    type: "Físico",
    price: 69.90,
    cost: 28.00,
    margin: 59.9,
    commission: 5,
    active: true,
    stockMin: 15,
    stockMax: 150,
    currentStock: 68,
    provider: "Distribuidora Tech Brasil",
    tags: ["varejo", "acessorios"],
    typeAttributes: { barcode: "7891234560036", ean: "7891234560036" }
  },
  {
    id: "prod-4",
    sku: "ACES-SUP-MG",
    name: "Suporte Veicular MagSafe com Indução",
    category: "Acessórios",
    type: "Físico",
    price: 89.90,
    cost: 32.00,
    margin: 64.4,
    commission: 5,
    active: true,
    stockMin: 8,
    stockMax: 60,
    currentStock: 35,
    provider: "Distribuidora Tech Brasil",
    tags: ["varejo", "veicular"],
    typeAttributes: { barcode: "7891234560043", ean: "7891234560043" }
  },
  {
    id: "prod-5",
    sku: "AUD-CX-WTR",
    name: "Caixa de Som Portátil Waterproof 15W",
    category: "Eletrônicos",
    type: "Físico",
    price: 249.90,
    cost: 110.00,
    margin: 55.9,
    commission: 5,
    active: true,
    stockMin: 5,
    stockMax: 40,
    currentStock: 18,
    provider: "Global Imports Eletrônicos",
    tags: ["varejo", "audio"],
    typeAttributes: { barcode: "7891234560050", ean: "7891234560050" }
  },
  {
    id: "prod-6",
    sku: "MOD-TSH-DF",
    name: "Camiseta Tech Dry Fit Antibacteriana",
    category: "Vestuário",
    type: "Físico",
    price: 89.00,
    cost: 35.00,
    margin: 60.6,
    commission: 5,
    active: true,
    stockMin: 10,
    stockMax: 80,
    currentStock: 50,
    provider: "Atacadista Master Varejo",
    tags: ["varejo", "moda"],
    typeAttributes: { barcode: "7891234560067", ean: "7891234560067" }
  },
  {
    id: "prod-7",
    sku: "MOD-MCH-AF",
    name: "Mochila Executiva Antifurto Impermeável",
    category: "Acessórios",
    type: "Físico",
    price: 199.90,
    cost: 85.00,
    margin: 57.4,
    commission: 5,
    active: true,
    stockMin: 5,
    stockMax: 30,
    currentStock: 12,
    provider: "Atacadista Master Varejo",
    tags: ["varejo", "viagem"],
    typeAttributes: { barcode: "7891234560074", ean: "7891234560074" }
  },
  {
    id: "prod-8",
    sku: "UTIL-GRF-75",
    name: "Garrafa Térmica Inox 750ml com Vácuo",
    category: "Utilidades",
    type: "Físico",
    price: 59.90,
    cost: 25.00,
    margin: 58.2,
    commission: 5,
    active: true,
    stockMin: 8,
    stockMax: 50,
    currentStock: 4,
    provider: "Atacadista Master Varejo",
    tags: ["varejo", "utilidades"],
    typeAttributes: { barcode: "7891234560081", ean: "7891234560081" }
  },
  {
    id: "prod-9",
    sku: "CAB-USBC-2M",
    name: "Cabo USB-C Trançado Reforçado 2m",
    category: "Acessórios",
    type: "Físico",
    price: 39.90,
    cost: 14.00,
    margin: 64.9,
    commission: 5,
    active: true,
    stockMin: 20,
    stockMax: 200,
    currentStock: 80,
    provider: "Distribuidora Tech Brasil",
    tags: ["varejo", "cabos"],
    typeAttributes: { barcode: "7891234560098", ean: "7891234560098" }
  },
  {
    id: "prod-10",
    sku: "ENER-PB-20K",
    name: "Power Bank 20.000mAh Turbo Quick Charge",
    category: "Eletrônicos",
    type: "Físico",
    price: 219.90,
    cost: 95.00,
    margin: 56.7,
    commission: 5,
    active: true,
    stockMin: 5,
    stockMax: 40,
    currentStock: 0,
    provider: "Global Imports Eletrônicos",
    tags: ["varejo", "baterias"],
    typeAttributes: { barcode: "7891234560104", ean: "7891234560104" }
  }
];
