export { ConfigEmpresaFiliais, ConfigEmpresaEquipe, ConfigEmpresaPermissoes } from "./sections/SettingsEmpresa";
export { ConfigCRMCampos, ConfigCRMFunis, ConfigCRMOrigens, ConfigCRMProdutos } from "./sections/SettingsCRM";
export { ConfigCRMSLA } from "./sections/SettingsCRMSLA";
export { ConfigCRMGatilhosIA } from "./sections/SettingsCRMGatilhosIA";
export { ConfigProdutividadeCategorias, ConfigFinanceiroCategorias, ConfigFinanceiroSquads } from "./sections/SettingsProdutividade";
export { ConfigEngajamentoModelos, ConfigEngajamentoAutomacoes, ConfigBusinessDashboard } from "./sections/SettingsEngajamento";
export { ConfigIntegracoesApps, ConfigIntegracoesSMTP, ConfigIntegracoesSDR } from "./sections/SettingsIntegracoes";
export { ConfigNotificacoesPreferencias } from "./sections/SettingsNotificacoes";
export { ConfigSistemaBackups } from "./sections/SettingsSistema";
export { ConfigRodizioLeads } from "./sections/SettingsRodizioLeads";
